#!/bin/bash

go build
if [ $? -ne 0 ]; then
    exit 1
fi

./nasp --reference ../nasp/benchmarks/Ecoli/reference.fasta ../nasp/benchmarks/Ecoli/external/*.frankenfasta

#go tool pprof -svg nasp cpu.pprof > cpu.svg
go tool pprof -svg nasp mem.pprof > mem.svg
#go tool pprof -total_delay -contentions -mean_delay -lines -svg nasp block.pprof > block.svg
go tool pprof -svg nasp block.pprof > block.svg

#open cpu.svg mem.svg block.svg
open mem.svg block.svg
